# Analysis of MOVE Index versus Bond Prices

# Overview

As with many Hedgeye subscribers in the spring of 2022 I have a portion of my portfolio invested in government bond ETFs. Also along with other Hedgeye subscribers I look at the ^MOVE index to see what direction bonds are likely to move in the future. How well does the ^MOVE index correlate to bond prices? Does a significant move in the ^MOVE index mean bonds will increase in price?

# TL;DR

Yes, the direction of the ^MOVE index can be used as an indicator of bond price movement, and a more extreme move in the MOVE index in the negative direction correlates more strongly to a positive move in bond prices.

In [10]:
import pandas as pd

To get data for my analysis I visited finance.yahoo.com and downloaded historical data for the ^MOVE index, IEF (7-10 year treasury bond ETF) and TLT (20+ year treasury bond ETF). This data could have all been combined into one dataframe using code, but for the sake of laziness, I simply copied and pasted the data for the closing price for each asset going back as far as data would go (Nov 13th 2002).

In [11]:
data_df = pd.read_csv('move_tlt_ief.csv')

In [12]:
data_df.head()

         Date        MOVE        IEF        TLT
0  2002-11-13  122.879997  86.129997  88.449997
1  2002-11-14  130.289993  85.660004  87.650002
2  2002-11-15  132.350006  84.900002  86.540001
3  2002-11-18  129.139999  85.129997  87.019997
4  2002-11-19  126.489998  85.620003  87.949997

My first and simpliest analysis was to look at a simple correlation. As expected, the MOVE index and bond prices are inversely correlated. The MOVE index is a measure of how risky bond investors precieve investing in bonds to be. We would expect that as bond investing gets less risky, that bond prices would go up, which is exactly what we find to be the case here.

In [13]:
data_df.corr(method='pearson')

          MOVE       IEF       TLT
MOVE  1.000000 -0.435471 -0.447911
IEF  -0.435471  1.000000  0.966260
TLT  -0.447911  0.966260  1.000000

Next I created a new column in order to track the rate of change of the MOVE index over time. The value in each individual row of the dataframe is the percentage change in the MOVE index over the previous 20 datapoints. I chose 20 days, which is pretty arbitrary, but it seems like the right number to use right? If anyone has a smarter way to choose this number, please hit me up [@paulknick](https://twitter.com/Paulknick) on Twitter.

In [14]:
data_df["change"] = data_df.MOVE.pct_change(periods=20) # 20 days

In [15]:
data_df.tail(20)

            Date        MOVE         IEF         TLT    change
4903  2022-05-06  122.720001  101.150002  114.139999 -0.009684
4904  2022-05-09  122.720001  101.139999  112.860001  0.000408
4905  2022-05-10  125.220001  102.309998  115.889999  0.020788
4906  2022-05-11  126.760002  101.930000  114.739998 -0.023947
4907  2022-05-12  118.050003  103.120003  118.019997  0.002207
4908  2022-05-13  118.730003  102.870003  116.980003  0.020631
4909  2022-05-16  118.730003  102.980003  116.209999 -0.007772
4910  2022-05-17  117.949997  102.349998  114.709999 -0.035726
4911  2022-05-18  119.459999  102.260002  114.720001 -0.026723
4912  2022-05-19  114.860001  103.900002  118.639999 -0.082001
4913  2022-05-20  115.050003  103.300003  117.089996 -0.119672
4914  2022-05-23  115.050003  103.570000  117.709999 -0.119672
4915  2022-05-24  110.190002  103.739998  117.900002 -0.162881
4916  2022-05-25  111.150002  104.470001  119.610001 -0.140172
4917  2022-05-26  105.690002  104.370003  119.019997 -0.187687
4918  2022-05-27  102.489998  104.449997  119.360001 -0.203899
4919  2022-05-31   98.480003  103.620003  117.180000 -0.235047
4920  2022-06-01  107.120003  103.269997  117.029999 -0.207516
4921  2022-06-02  109.379997  102.910004  116.629997 -0.135062
4922  2022-06-03   99.269997  102.360001  115.089996 -0.186245

Next I wanted to look at the most extreme examples, so I started with the 25% most extreme moves in the MOVE and found that it roughly equaled -10%.

In [16]:
data_df.describe()

              MOVE          IEF          TLT       change
count  4923.000000  4923.000000  4923.000000  4903.000000
mean     83.145659    98.973226   111.577859     0.012742
std      30.600767    11.525348    21.560231     0.171502
min      36.619999    79.629997    80.889999    -0.595113
25%      60.905001    87.160004    91.300003    -0.092890
50%      75.900002   101.919998   112.510002    -0.015552
75%      98.099998   107.220001   124.795002     0.092121
max     264.600006   123.250000   179.100006     1.495807

I made a dataframe that just contained the samples that had only changed greater than -10% over 20 days. That dataframe was called "extreme_df".

In [17]:
extreme_df = data_df[(data_df.change < -0.1)]

The correlation for this more extreme dataset was -.53. Remember that for our base dataset the correlation was -.43. This outcome was also expected, the more extreme the change in the MOVE in the negative direction resulted in more extreme moves in the price of bond ETFs in the positive direction.

In [19]:
extreme_df.corr(method='pearson')

            MOVE       IEF       TLT    change
MOVE    1.000000 -0.534632 -0.531760 -0.050207
IEF    -0.534632  1.000000  0.967112 -0.162047
TLT    -0.531760  0.967112  1.000000 -0.186239
change -0.050207 -0.162047 -0.186239  1.000000

Next I did the same thing again, getting the top 25% of the 25% (so 6.25%) most extreme moves in the MOVE in the negative direction. This roughly equated to a 20% move in the MOVE index over a 20 day period.

In [18]:
extreme_df.describe()

              MOVE          IEF          TLT       change
count  1135.000000  1135.000000  1135.000000  1135.000000
mean     78.067736   100.726405   114.728467    -0.169189
std      28.249162    11.566404    23.255822     0.064558
min      36.619999    80.620003    81.199997    -0.595113
25%      57.799999    90.465000    92.925003    -0.199742
50%      72.129997   102.430000   116.150002    -0.151840
75%      90.799999   108.600002   126.509998    -0.120779
max     212.899994   122.889999   171.929993    -0.100025

In [20]:
extreme_extreme_df = extreme_df[(extreme_df.change < -0.2)]

In [22]:
extreme_extreme_df.describe()

             MOVE         IEF         TLT      change
count  282.000000  282.000000  282.000000  282.000000
mean    82.154645  101.944433  117.428865   -0.257836
std     31.291917   11.871380   25.745106    0.062378
min     36.619999   81.680000   81.419998   -0.595113
25%     58.725001   92.177502   95.512499   -0.275778
50%     75.779999  101.815002  108.219998   -0.238204
75%     94.549999  108.927500  128.557499   -0.216082
max    189.000000  122.750000  171.929993   -0.200000

Here we see the same outcome as before, but less of a change. As we went from 100% of the sample size, down to 25% of the sample size, then further down to 6.25% of the sample size we have seen the correlation move -.43 &rarr -.53 &rarr -.59 for IEF and -.44 &rarr -.53 &rarr -.54 for TLT.

In [23]:
extreme_extreme_df.corr(method='pearson')

            MOVE       IEF       TLT    change
MOVE    1.000000 -0.594063 -0.546117  0.058308
IEF    -0.594063  1.000000  0.968459 -0.356128
TLT    -0.546117  0.968459  1.000000 -0.427756
change  0.058308 -0.356128 -0.427756  1.000000